---
# Synopsis: Suppress APIM policy rules for all files in the 'src/suppressed' folder
apiVersion: github.com/microsoft/PSRule/v1
kind: SuppressionGroup
metadata:
  name: 'SuppressAPIMPolicyRulesForFilesInSuppressedFolder'
spec:
  rule:
  - 'APIM.Policy.BackendBasePolicy'
  - 'APIM.Policy.FileExtension'
  - 'APIM.Policy.InboundBasePolicy'
  - 'APIM.Policy.OnErrorBasePolicy'
  - 'APIM.Policy.OutboundBasePolicy'
  - 'APIM.Policy.UseBackendEntity'
  - 'APIM.Policy.ValidXml'
  if:
    name: '.'
    contains:
    - 'src/suppressed/'


---
# Synopsis: Suppress all rules for 'src/suppressed/global.cshtml'
apiVersion: github.com/microsoft/PSRule/v1
kind: SuppressionGroup
metadata:
  name: 'SuppressRulesForGlobalCshtmlInSuppressedFolder'
spec:
  rule: []
  if:
    allOf:
    - name: '.'
      endsWith: 'src/suppressed/global.cshtml'
    # The filter on name is actually enough, but this shows a sample of how to filter on level
    - field: 'level'
      equals: 'Global'