###################################################################################################################
# Install the VS Code REST Client extension: https://marketplace.visualstudio.com/items?itemName=humao.rest-client
#
# Configure an environment with the following settings:
#   - apimHostname: The hostname of your API Management instance
#   - apimSubscriptionKey: The subscription key of your API Management instance
#
# See: https://github.com/Huachao/vscode-restclient#environment-variables
###################################################################################################################


GET https://{{apimHostname}}/client-cert/validate
Ocp-Apim-Subscription-Key: {{apimSubscriptionKey}}
# Don't forget to enable 'allow tracing' on the subscription
Ocp-Apim-Trace: true

###
