trigger: none

# See https://microsoft.github.io/PSRule/v2/creating-your-pipeline/ for more information on running PSRule in a pipeline

jobs:
# This job should fail because not all files in the src folder conform to the APIM policy rules
- job: run_psrule_on_src
  displayName: 'Run PSRule on src folder'
  condition: false
  pool:
    vmImage: 'ubuntu-latest'
  workspace:
    clean: all
  steps:
  - checkout: self
  - task: ps-rule-assert@2
    displayName: 'Analyse src folder with PSRule'
    inputs:
      path: '$(Build.SourcesDirectory)/validate-apim-policies-with-psrule/'
      inputType: 'inputPath'
      inputPath: '$(Build.SourcesDirectory)/validate-apim-policies-with-psrule/src/'
      source: '$(Build.SourcesDirectory)/validate-apim-policies-with-psrule/.ps-rule/'
      option: '$(Build.SourcesDirectory)/validate-apim-policies-with-psrule/.ps-rule/ps-rule.yaml'
      outputFormat: 'None'

      
# This job should succeed because all files in the src/good folder conform to the APIM policy rules
- job: run_psrule_on_src_good
  displayName: 'Run PSRule on src/good folder'
  condition: false
  pool:
    vmImage: 'ubuntu-latest'
  workspace:
    clean: all
  steps:
  - checkout: self
  - task: ps-rule-assert@2
    displayName: 'Analyse src/good folder with PSRule'
    inputs:
      path: '$(Build.SourcesDirectory)/validate-apim-policies-with-psrule/src/good/'
      inputType: 'inputPath'
      inputPath: '$(Build.SourcesDirectory)/validate-apim-policies-with-psrule/src/good/'
      source: '$(Build.SourcesDirectory)/validate-apim-policies-with-psrule/.ps-rule/'
      option: '$(Build.SourcesDirectory)/validate-apim-policies-with-psrule/.ps-rule/ps-rule.yaml'
      outputFormat: 'None'


# This job execute the Pester tests
- job: run_pester_tests
  displayName: 'Run Pester Tests'
  pool:
    vmImage: 'ubuntu-latest'
  workspace:
    clean: all
  steps:
  - checkout: self
  - task: Pester@10
    displayName: "Execute Pester Tests"
    inputs:
      scriptFolder: '$(Build.SourcesDirectory)/validate-apim-policies-with-psrule/tests'
      resultsFile: '$(System.DefaultWorkingDirectory)/TestResults/Test-Pester.xml'
      CodeCoverageOutputFile: '$(System.DefaultWorkingDirectory)/TestResults/Pester-Coverage.xml'
      usePSCore: false
      CodeCoverageFolder: '$(Build.SourcesDirectory)/validate-apim-policies-with-psrule/.ps-rule'
      PesterVersion: 'OtherVersion'
      preferredPesterVersion: '5.*'

  - task: PublishCodeCoverageResults@2
    displayName: 'Publish Code Coverage'
    inputs:
      summaryFileLocation:  '$(System.DefaultWorkingDirectory)/TestResults/Pester-Coverage.xml'
      pathToSources: '$(Build.SourcesDirectory)/validate-apim-policies-with-psrule/.ps-rule'
      failIfCoverageEmpty: true

  - task: PublishTestResults@2
    displayName: 'Publish Pester Test Results'
    inputs:
      testResultsFormat: 'NUnit'
      testResultsFiles: '**/Test-Pester.xml'
      searchFolder: '$(System.DefaultWorkingDirectory)/TestResults'
      mergeTestResults: true
      failTaskOnFailedTests: true
