trigger: none

jobs:
- job: run_psrule
  displayName: 'Run PSRule'
  pool:
    vmImage: 'ubuntu-latest'
  workspace:
    clean: all
  steps:
  - checkout: self
  - task: ps-rule-assert@2
    displayName: 'Execute PSRule on src folder'
    inputs:
      path: '$(Build.SourcesDirectory)/validate-apim-policies-with-psrule'
      inputType: 'inputPath'
      inputPath: '$(Build.SourcesDirectory)/validate-apim-policies-with-psrule/src/'
      option: '$(Build.SourcesDirectory)/validate-apim-policies-with-psrule/.ps-rule/ps-rule.yaml'
      outputFormat: 'None'
