trigger: none

jobs:
- job: deploy
  variables:
    keyVaultName: 'kv-my-apim-client-certs'
    clientCertificateName: 'my-sample-client-certificate'
    clientCertificatePassword: 'MyPassword' # Should be a secret variable
    clientCertificateSecureFileName: 'my-sample-client-certificate.pfx'
    
  steps:
  - task: DownloadSecureFile@1
    name: clientCertificate
    displayName: 'Download my-sample-client-certificate.pfx'
    inputs:
      secureFile: '$(clientCertificateSecureFileName)'

  - task: AzureCLI@2
    displayName: "Import my-sample-client-certificate.pfx into Key Vault"
    inputs:
      azureSubscription: 'Visual Studio Enterprise 1'
      scriptType: 'pscore'
      scriptLocation: 'inlineScript'
      inlineScript: |
        az keyvault certificate import `
          --file '$(clientCertificate.secureFilePath)' `
          --vault-name '$(keyVaultName)' `
          --name '$(clientCertificateName)' `
          --password '$(clientCertificatePassword)'